services:
  - type: worker
    name: aksjebot
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
    autoDeploy: true
